namespace: patchman

resources:
  - namespace.yaml
  - secret.enc.yaml
  - server.yaml
  - worker.yaml
  - cronjob.yaml
  - service.yaml

helmCharts:
  - name: redis
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: redis
    namespace: patchman
    version: 27.0.14
    skipTests: true
    valuesInline:
      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          storageClass: zfs-quick

images:
  - name: ghcr.io/klaernie/patchman
    newTag: 4.0.21@sha256:64383ba9531987289e7817cb0b7445ba54cb1226e1d9b57f1c9f052aa812d4cc
