namespace: patchman

resources:
  - namespace.yaml
  - secret.enc.yaml
  - server.yaml
  - worker.yaml
  - cronjob.yaml
  - service.yaml

helmCharts:
  - name: redis
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: redis
    namespace: patchman
    version: 21.0.2
    skipTests: true
    valuesInline:
      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          storageClass: zfs-quick

images:
  - name: ghcr.io/klaernie/patchman
    newTag: 3.0.10@sha256:0466332f1af80f7f3da7e6e69f12d81f74b79ff17ad7cf3ec4f5fa2e9b3a55d1
