namespace: patchman

resources:
  - namespace.yaml
  - secret.enc.yaml
  - server.yaml
  - worker.yaml
  - cronjob.yaml
  - service.yaml

helmCharts:
  - name: redis
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: redis
    namespace: patchman
    version: 25.4.1
    skipTests: true
    valuesInline:
      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          storageClass: zfs-quick

images:
  - name: ghcr.io/klaernie/patchman
    newTag: 4.0.21@sha256:abddb08e8fa48892ce4ca75017a9cf599f8b8a5e29a8211e016bce06f9ac33ce
