apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: patchman
    namespace: patchman
spec:
    secretTemplates:
        - name: patchman
          stringData:
            ADMIN_EMAIL: ENC[AES256_GCM,data:LHt5JykwDtN9ydtQ8z+qVc7VYHs0lYa07jORbQ==,iv:2DySyXPKhPGIWsEFMay9A35A2+Wx1QC1pO9Ed1I7s9A=,tag:EZDCLXleCh8hQamduJMQ4w==,type:str]
            ADMIN_USERNAME: ENC[AES256_GCM,data:YfC6ocuq,iv:cDwVrZ048K6z50nVqi6JZX+B1sdLBIUy7ToDZaGmQ94=,tag:DVTr/Ne1DTHYHBOFGIqazQ==,type:str]
            DB_ENGINE: ENC[AES256_GCM,data:OgLdPjJoLp2KSA==,iv:sihRrORlgfoDBjQvTiNsE1XM7LoRovKPxoF7wHsEZfA=,tag:7X97tsey5VSC2VWTkuOAPw==,type:str]
            DB_HOST: ENC[AES256_GCM,data:kpfYDGVxWofuYakNKx73M11lvzjE,iv:5n60R2RTbaAdGaqNczhnWG2plV3HGNmwdugkEI4Bvws=,tag:d5MSWAAO+yRr6mgRYb94rA==,type:str]
            DB_NAME: ENC[AES256_GCM,data:aSkck5YllDc=,iv:J7trbAv1O22PrKnxHB4UoHOvlGyKxDp3L10wmq/uCUo=,tag:AJIytkjrIWgkQTz4X0idRA==,type:str]
            DB_PASSWORD: ENC[AES256_GCM,data:Q1+939BDUUoh1ZYpyAAB0gpO,iv:kgHrboGUBKu7E9y14isdzKnDMDb9OAauZ0vlLn51LZ8=,tag:I+DHDHoOH8Q8Ee5RuKf26Q==,type:str]
            DB_USER: ENC[AES256_GCM,data:F0ew30WPcJ8=,iv:e4dRGAujKb94T2kLxZKHwIP/Wecbxbyg77XCvdt5p4g=,tag:RTIPzVLuEu6DUveRrna0QA==,type:str]
            SECRET_KEY: ENC[AES256_GCM,data:M+ehRO2tnvun34eE7Ury096BolHAXuUTR84WExC9/iZvnmQ=,iv:ARPfi5Wvbs6hJUfjoEc2DToFSuF9t9fkb4QYH6k3JxQ=,tag:K8STr1PblsgcgVtZwsJHcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfxd6zqm4x755qpxd2h4fl5uqnu07hrpyv2cstdey0lg5lc5x47qzsvrn5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWTZoK04yMzI5U1NKM1Rh
            WjF5TlFoSTJNcWZUSy8wQ1ZXMWRaZm0rOWpRClQya3djTFpwZGYxS2NkUlFTMGRP
            a05ZUU5CbEVrdVl0K3NJallyanNSS2sKLS0tIGdYKzhIU0N4YllxZHlzdmpDTmxH
            RCtYYlFNc3RMQ3MzVkJmemFqWkhON1kKpsxYaMks8CVyRkR6yBBykfHXq3PNerNm
            tEQ65hHBjiDumyIieF3TCrf6X31+nhWZHXVQQjt9c21Ta/eXZ8WO+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T21:23:29Z"
    mac: ENC[AES256_GCM,data:nTfxZFwTHPS9fDpdk0FzqyRXLw3z9wLx/bVKUNw5WeMVhopuZ3+RWhbGIFc+XtpilXV2YWbVFkio9celvkcGTCO0vVP75kUfO+TYndSZwsq+5Bie+C/gg3yz0vOYiXeTSy8pIFSADlgNb2p6ym13Izg7zNB/6C2COfjprOnchzs=,iv:/sF3izN1p9irVaBYG6O9E7hzthhV8uXzP/PDszOjOOU=,tag:kVsdToHgcfUSlorCTczokA==,type:str]
    pgp:
        - created_at: "2024-10-06T21:19:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz9aZqoHT9PNARAAp2T04XfJrrAw3hEXssMVg1fNHJbvVi/bChEPRyNGEUWe
            E2RFB0psaxcyX/i9MBZNy+3kADaqSdzZLu0boUwERRmgXcmd69ErMsTkADXbJno1
            82DDIZs4KpTTT208dE971+nzGCARgUNmMrTC7p4klZI3vY6Zf45GXGJAztdjaN22
            JbvZNTKYtsiTzoH+BhIFDDy6n8LO0VyEdWzRCVUcZnYidihYxLDPWLJdwBPOPvtj
            PZ9elNHbKt/SruSbBScnISzwcWEdKexucGfCqXWTej647Xs6r+Ix9QY2qQP/WpQb
            nhHsJ+kpuIcYcL8B7mx4i64+Nr612ZW2GqNDSLHd1fSWswk7GVlMqPEG+WgewMCA
            m62iXrbzfzkyT5PPjzWJiamZOqzvLNwxakjE7wYfh/YnutNV+zuOuXuk7drhH9Ad
            FLY6b8r2ZPdDS/CDtojqX7WNqc79dFmLOm0oBDjSVWFgoBZ77O8UVv3YFTCgAk1O
            25N1FE3hQSb0ljqzMQVgdw8ZDM6C8J07o5pnb/GXaED/Zzb3Nuf+vqVNXDkqt4Yo
            nbZJwoXIVwFPYB/YVNU6UJ4pDAMXEiQVFH6HZD4wtiIpMwRHtwSjMj0UO4ofyPyD
            sy+6l6XhCAwQ2cCK9tBR2BYsh7npnBfBadvMSdJNCJoA83BVScVKc5C2OZ923KfS
            XAEKLSBOTFPoaXLSm9fmuACYD3earXCT388wFTrAy/3P21CI6khcw1nzJWo9DQeF
            vuS/VepmOk0zbHB0JN4JCAz0RHbMO8qMWlwOYxJYKSPMGFtk7zYfAobc3N1I
            =tdJb
            -----END PGP MESSAGE-----
          fp: 6528912C6687A3E2
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
