apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-gpg-keys-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-gpg-keys-cm
  namespace: argocd
data:
  6528912C6687A3E2: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQINBFwERkwBEAC0D0xyyDjdBk1Qng0WiCdd1s4TofJOnXi6s7qnENgcu1MxStqT
    KGf7H2NseQX1a4RMCeWKcKn14KMDVSybDV94eUDKYCvBGVeBHRclgxPJpezGHhuI
    1CX2Bijbo6bwp/pB/RF5Nkgv7aNjySoBfqHmZ6eZFHNoxLKTXkJQAg3c4GSL1Rdz
    /73h0Gj/aZNzdOiqFNMIpqCo3zLlWuZpNVL/BBjYcR3Z1/5uRdEDYQRa4bTgl5Dg
    1X/cKHjhmubMArZBDQZqfwwXrJUgOPiOoFCB+x9KrOUn5l3dFUzC3jiUt8b6+fPl
    8JOwJAXJldkwLZlDRIrub/6WUph2mIUevXhKfekacvFiCHbIbUlUEoy3oiOVrfpK
    AIiT+ANxfjMJeEkvTCnJ1txPgnqJ0Ev2cSvPpSFaUSbpOZ75jncpcMYosctxYUzr
    fsTCMMMPeYH79NzRCNCV7Dz1RknnZEnKPvFLp+1/iBLAGoO7dCS2x5KR107EbinT
    ndJYpWh1Tb2wkkgFU71Php0G/mTSd7cC2FyDIav2Y0Cga9KQWWsdXdEb2J5pdDJW
    klWxd8vwbS3UpJx5UFKYfFfcp29izYYPHttKSJRPoiaN9MGUg5NDKuW08vyuoRwI
    9mhI+gVs+u8xW1Bl1VkupsRGGfGJkl+/8xROU1KbsaT40jZL3bOQIMQYMwARAQAB
    tCRBbmRyZSBLbMOkcm5lciA8a2FuZHJlQGFrLW9ubGluZS5iZT6JAk4EEwEKADgW
    IQQmWWY18FnycKuHsAxlKJEsZoej4gUCXARGTAIbDwULCQgHAgYVCgkICwIEFgID
    AQIeAQIXgAAKCRBlKJEsZoej4kK+EACBcJ1Picj07vat3TzRzQ6LOZd+TNhI5cQC
    nivXObLWGrBiDGWrTfEqx0GsuqEIIB9r4mz+snxOvO8HD3KSduGuOXY+DC7BUeXi
    DkLLVNsy8Qv3Y7GBtlq2cYFRz0GCKZ6Md3TDLAMgS5BC43RylcQazkqSv8eF3tG/
    SLc5T3fAm9f95uMqzioItmvzulcNtYbAINYqvt/rNYkPDsTD1wD6a1aGIyeEGl0d
    kqrj8vdvPowJ2tMuRE6r2iuY/+IQWzOSPLku8DvMS7uuovxVfkBUta2nRU41wQcn
    nlizdS8x23yfEVLZQrMeuAraAW5Rfkr1nY5Mp9qPuNg+MuJSO2gmQtTgwe+5xIdV
    P0X42t5+2f5Mq9zG5NIS4yxrsKhrYlz/IwW35hWPQl+VZQ3bF3SV74ppzVd6NzpM
    /AxfkqaU8Rzzynu9hr080V6o+zzI7HqZZJjUBbDAcumKfr/czW/zLU8rbkfHaOk0
    mURBO+JZW8ltAgwUBiKyeJ1btryJIdmzICDqJdiRY3Azp/bVCmj1UV2Z3+mlbTt3
    +Fz8EBBoYDseYIdDj33mpmFqRCwUKvs6RyHVjx2YMwI2S65MMXf6bbqkDft57NFG
    u/WZpXdvV1GrZQz43I6+mXWk3gfjv0NI12rUuDL2AqCYuV+WGmFi2LaRmIWL9A5p
    RSvNbx0RubkCDQRcBEbUARAAtihtGDTZPJ3Rn1V7hDDtK0ptBO/f8U1F/N+oW94r
    BtED+OVAHdEoOYIsOPkrooS/GpKEZiu3d/y+ytBEEy89CQ0iBRNBqmU4U64MtkWm
    PVPM4KRzdOG5CSZaTvXaKrvrGfiwl6imPv41iByLtC7uVI5/NDRNwHJI1867Wpha
    n0j7UuJrxkgr2Soe6mntSHAcxLkqQQYTeue1NfkgLc1GrabBnWoSkwAZ5jMqadvg
    RmwHjwXoykMZY/An+82qfWW1xzGKRR9/XriBgwPt81LWL/rdZ3BmWiv70UZBu/T5
    JY7/XQn6eX5Rctb+jr8aCkGuwnst27CwRuTizEOqJeuBaVDsq65zfw2fzw20bBMM
    HaeK8ick94dXQnUJunlqWsKiEwoKdz9c2JotJfVQ9h05t/c9pxbg4tgZQJkqz7gD
    x7RENXRcbJjsSv+JDSohapgZry4huP4t07u/M/wt+h+zg1Cjj4f685eecDaBaFBw
    uekN6X3yrDOFMqvDg0GQWO0bxcTu66vqdkTrQUQsE0R9IXMyntdCceZTPvnxi2yp
    F1Kg2PMhYtw2XZ2fJ+Rof5VFf2iGp2TtvD9iuclD/7hW1Rq+J+7JTRRrL4BwBqvq
    EqzUYYfB67JxeLfUe5cZng6oDLL+PrGTjma1rMwaebnBZeswdVtl6STd6AYTRwDY
    jX0AEQEAAYkCNgQYAQoAIBYhBCZZZjXwWfJwq4ewDGUokSxmh6PiBQJcBEbUAhsg
    AAoJEGUokSxmh6PiBmEP/R4drTqW8BH46js2FuBoL++krKTcTXDILp91A9MKvSU6
    jxTJgdvP/C9eNEFfwXJ64zCepMndjGJIuzXnME4rxvc6JxiVK+JkBI79bYSucVPb
    mlzTCVHc4GrTwerl0GbXW8F0CoDhZNBA50FGF4C4iTGGryxF5zpoLiBtncVbkOus
    ffm/Vs29JWsyJPtcV5iyLqQ055U1ZCcjdxhyc1+i5J9Sn1HqcMhDWxYkOYzoSF+u
    +2rzG0z3rI+7xc8izJD1UHBHfsZqiI3etqucpN3Y10JdphaVJfQwj9T/+3sLr3tL
    ATZPGCKYJoEa84lPFqaVP2+NDIIxUlTxLAqqzppEl0cYVRJ9pqe8da6LR4CP/E6J
    /cvxT0UVc4OF7NBqhfRG0iJ4Ta1X/ZkvZ1wTxWLs2pmLnGzd7Jth7y+XVDWLc0eL
    JTLhVJbDYVOMi1n0GqbACgiXQ5r1wS/kMIJfrJ6U5ekqAM3Hz0sw8vx1idHV4mvh
    7W1BIC1UI5SXMbJ/xrVZgllNgjfBjFGkVlSoMsouQzrlm2KpK2kJY/UVAQCD67zl
    ESufmsQagW2KSGxyNINrvFXFoFlytG1v0p49njy9Q1LD6H2kXy3A5PQJ/wbieC+e
    cy4ShkJEAiqzhWVZ27tgEqNvL51tBPbiXqFBrCSYwB5Qs2toJYjbPmG/IX9SQjes
    uQINBFwFfbcBEACqgs8zD/eHs0IwEY291K+PJ2/rzg/cUiNesAUGU727HxEyrwQs
    1DdNS+6lNcTKDxl0zHD+t4+ctJmnXT10kcnG1CoIo4+hX9tCMri5bDWBjSx1eLMp
    67dIBxENkX3U7DdGJ05M28JDHNBmfffWHFXpS5wOv96S2YTz4I6Y3NzQmIEY1ZMk
    6+CkwU9T1FvsOKA+WLyrR4xPVltGvZNZBAsPhWLCwkrXggByGdanq+dZSPcVhgPz
    tT7vYiUNB1MvxukUmIkcNhARqJAy3YY56qCYZPAcNgbrWMvWQIjFF7BJgX5s9Fw2
    so17iAd9NdoHbFJ4eP7jQfg8f3UUk4TNSAC+wNlC+lAC530xuFm6V+ITfb7gN+YV
    UjH15BMI779G+vWOFsMh6E1oLUtwDifWykLs36ZB7cDxeyeowzB4tLHvFdnTkp/q
    wthAQSm5fEmpNCY0wPZP5vwTI1NcFtZxW/Bo2ucJRwxxb1v/D+rDKt1qVbCL7RFi
    xrpQpAWZVtlXHMdNbkD0nR5Mu6MHAKZq2Y0k+ICAe1s0+TQozPAYHmF7mtiniyka
    Vf+CwW/2Cq5SW5Y9IujsyttY+ccanEKV+sxOtIBCQubRCdRqz2m/xWwJkZeVfkJA
    5n42d6A/QCjZcHHG+z3fNSh1eWEMMdIiTho65Y4fq0703NnlPT6TWHg+YwARAQAB
    iQI2BBgBCgAgFiEEJllmNfBZ8nCrh7AMZSiRLGaHo+IFAlwFfbcCGwwACgkQZSiR
    LGaHo+L0YQ//a3Wy++NUe+Nmg9VC4zP5W9qBamy9pn20UVK1vaKxf7jfSGfaG1X2
    ZCCzKZIZboiWU48ZiLoanMwcPow1oI05Xb2W9sGYEWcWKvmWtgPUlcvosPy5/mUf
    jQHI/6KXO3U3tthvzqc90EftphtBmEmE+iSe5yNjkti5+9WngdUk3+IW625MFZLj
    3lTG9LYHumhILrsP4XWGvDMH+N+JqSWWKzYMmNItBZN1i95JSNduzSgot6Oc8KQF
    i5LAVgOFQKKujrRdwXGqcz5QHRFD8VgS5E5DxxMIPhlijNWFhM5KVp4ksvfzEPtr
    p2gnRJNLDr+rfd6WRN+uzEUuSlzwBDH2qkSX8Wnq3u2FONXdbIVDfXRyX7sbQ3YO
    kksJx8+DvpnHjqfhOJVCzQcOY8EvD3BInCoQpOpeqKjdhjzoBmWgXL6DOH+uXA+P
    uxZ+Mr+9LnOWmJWkCidv+CY8g0UvVeWvllAv+KCJsjhFP+HxGJn+EyE+qI+ffkOB
    4JkuZqGvIOVJz6DATDVQa9Clto/34t1N24vjH+94HuXr1cSlvyWcKu7txj7QUFtz
    ZUMO7CFnJSfbO7fNhZZvjf4a+cWlOSgaD22VHYZy6GTN4SVUTuoLWypzeVGKBEVK
    vIjgDF75aYhEl5oo1SB1OSK4sMfrwfP7ItDHWl7bHBot5f7XzF9vD8c=
    =2jnB
    -----END PGP PUBLIC KEY BLOCK-----
