apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abs-metadata
  namespace: abs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zfs-bulk
  resources:
    requests:
      storage: 5Gi
