apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trilium
spec:
  project: macy
  source:
    repoURL: https://github.com/klaernie/k8s-macy.git
    path: trilium
    targetRevision: main
  destination:
    server: https://macy.ak-online.be:6443
    namespace: trilium
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
