apiVersion: v1
kind: ConfigMap
metadata:
  name: sso-pipeline-roles
  namespace: netbox
data:
  sso_pipeline_roles.py: |
    from django.conf import settings
    from netbox.authentication import Group

    def set_role(response, user, backend, *args, **kwargs):
      client_id = getattr(settings, 'SOCIAL_AUTH_OIDC_KEY', None)
      staff_role = getattr(settings, 'SOCIAL_AUTH_STAFF_ROLE', 'staff')
      superuser_role = getattr(settings, 'SOCIAL_AUTH_SUPERUSER_ROLE', 'superuser')
      print("looking for superuser role: "+superuser_role)

      roles = []
      try:
        roles = response['resource_access'][client_id]['roles']
        print("response: ", response)
        for role in roles:
          print("found oidc role "+role)
      except KeyError:
        pass
      user.is_staff = (staff_role in roles)
      user.is_superuser = (superuser_role in roles)
      user.save()
      groups = Group.objects.all()
      for group in groups:
        try:
          if group.name in roles:
            group.users.add(user)
          else:
            group.users.remove(user)
        except Group.DoesNotExist:
          continue
