apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-oidc
  namespace: netbox
data:
  netbox-oidc.yaml: |
    LOGIN_FORM_HIDDEN: 'true'
    REMOTE_AUTH_BACKEND: social_core.backends.open_id_connect.OpenIdConnectAuth
    SOCIAL_AUTH_BACKEND_ATTRS:
      oidc:
        - Keycloak
        - login
    SOCIAL_AUTH_OIDC_OIDC_ENDPOINT: 'https://keycloak.ak-online.be/realms/master'
    SOCIAL_AUTH_OIDC_KEY: netbox
    SOCIAL_AUTH_SUPERUSER_ROLE: admin
    LOGLEVEL: DEBUG
    SOCIAL_AUTH_PIPELINE:
      - "social_core.pipeline.social_auth.social_details"
      - "social_core.pipeline.social_auth.social_uid"
      - "social_core.pipeline.social_auth.social_user"
      - "social_core.pipeline.user.get_username"
      - "social_core.pipeline.social_auth.associate_by_email"
      - "social_core.pipeline.user.create_user"
      - "social_core.pipeline.social_auth.associate_user"
      - "netbox.authentication.user_default_groups_handler"
      - "social_core.pipeline.social_auth.load_extra_data"
      - "social_core.pipeline.user.user_details"
      - "netbox.sso_pipeline_roles.set_role"
