resources:
  - netbox-namespace.yaml
  - secrets.enc.yaml
  - configmap-netbox-oidc.yaml

helmCharts:
  - name: redis
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: netbox-redis
    namespace: netbox
    version: 27.0.13
    skipTests: true
    valuesInline:
      architecture: standalone
      auth:
        enabled: true
        existingSecret: netbox-redis
        existingSecretPasswordKey: redis-password
      master:
        persistence:
          storageClass: zfs-quick

  - name: netbox
    repo: oci://ghcr.io/netbox-community/netbox-chart
    releaseName: netbox
    namespace: netbox
    version: 8.3.30
    valuesFile: values.yaml
    skipTests: true

namespace: netbox

patches:
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/startupProbe/periodSeconds"
        value: 10
      - op: replace
        path: "/spec/template/spec/containers/0/startupProbe/failureThreshold"
        value: 90
    target:
      group: apps
      version: v1
      kind: Deployment
      name: netbox
  - patch: |-
      - op: add
        path: "/metadata/annotations"
        value:
          reloader.stakater.com/auto: "true"
      - op: replace
        path: "/spec/revisionHistoryLimit"
        value: 2
    target:
      group: apps
      version: v1
      kind: Deployment
