resources:
  - netbox-namespace.yaml
  - secrets.enc.yaml

helmCharts:
  - name: redis
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: netbox-redis
    namespace: netbox
    version: 21.0.2
    skipTests: true
    valuesInline:
      architecture: standalone
      auth:
        enabled: true
        existingSecret: netbox-redis
        existingSecretPasswordKey: redis-password
      master:
        persistence:
          storageClass: zfs-quick

  - name: netbox
    repo: oci://ghcr.io/netbox-community/netbox-chart
    releaseName: netbox
    namespace: netbox
    version: 5.0.0-beta.65
    valuesFile: values.yaml
    skipTests: true

namespace: netbox
