apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: netbox-secrets
    namespace: netbox
spec:
    secretTemplates:
        - name: netbox-app
          stringData:
            email_password: ""
            secret_key: ENC[AES256_GCM,data:zwZczZB5VZe3vbRSyj89FCcGNDaTn9Kopu2Ig21aNkibYJmrrIXBNRTfI0oX+rhy5Mv+JvvlakBe+hY=,iv:HONdizh8bO5rquNXdrMoOLP/ZoEXxdBtcoyFIQVJ5J0=,tag:f90KabYZ3WKzD3MphPtGJg==,type:str]
        - name: netbox-admin
          stringData:
            username: ENC[AES256_GCM,data:rqHaQCeZ,iv:hVUKwaorH9GwN1MvwIon0mMQbnPjU/wpeZ/5j6I5Qp4=,tag:hqFvjPm8x6hWs9f/UDiIzA==,type:str]
            password: ENC[AES256_GCM,data:qsL9wDtb5F6SHA==,iv:YFn3V+x/s7W7CGzqX/+47B8xjMSAFsu5Ssc3EkAkmi8=,tag:6oBoqyb/93qWl1d2sGmmtQ==,type:str]
            email: ENC[AES256_GCM,data:9FqVjNvf8/vzKy6ZN5jSs8V9zg==,iv:ruAmSvWMzy6UunXa2m69XiqSJh1s+IagNsNJd4c7+pU=,tag:ZKKj9rWmOzt2X/F4b6Colg==,type:str]
            api_token: ENC[AES256_GCM,data:Z/8HpHHpNPD27tXYwnAa57te3WvyE1nTYMp3tObBDWehgewNAzE3JouZDD8r6vMd,iv:MoZ1eL4C+fffRd7Jg1frwxmPx3qLtc3SW6E7t3v7t5k=,tag:ys4qBGhE7Cj4M2X0iwiihg==,type:str]
        - name: netbox-postgres
          stringData:
            db_password: ENC[AES256_GCM,data:PY919rapbl0YlwtaXM5ycoLX3fPMNo+ruuOpX5FHB9o=,iv:0Fd4fGXKxVJR6Kp6XowsT5w6jk+OlhXwul56UpEk5AQ=,tag:CdkO7zvhWkFa2INWiNXH2Q==,type:str]
        - name: netbox-redis
          stringData:
            redis-password: ENC[AES256_GCM,data:PpZjm5CbhlAGLQ==,iv:x7JYPbx7W0YESh2zHlxHUfPDNW+ZY25EJM4Gvc/AeLI=,tag:24H64wjbCtYBY6l043nDDA==,type:str]
        - name: netbox-proxbox
          stringData:
            proxbox.yaml: ENC[AES256_GCM,data:frjSnKqGHeLx29wYVYf5thCLMWHZa2Y98if7JuqjepEzMXGPsGPd0BNS5gC0XcNLGK63kcMozHEcOl76/2Vsxu0iEAx59iJ2Up8H9C3vHwvjvxgrU+AdS6fxHw6qnjWkwHTeJ9rO17pSVVxIx9jqP7pPl0U/jO+03SEGffFX1vfjMi/dkMRaXHkQ6m+krbh/WXDpRl4VrFe0GIj+3WbYCBavQZusRNrtX6tFHMvtI3q1RgYKwPE=,iv:jMBYqBOwi7O611kOAcDS3jd87YHEH6zVdOI5bDuN0+4=,tag:65XsV0FAE1TTFmuGdj7KOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfxd6zqm4x755qpxd2h4fl5uqnu07hrpyv2cstdey0lg5lc5x47qzsvrn5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWFBFSlljbVEzcUFyWC9T
            eTIwYUJkWWJqUmJPWStsMktLNWg1bGVST1dRClRna1AxRm9SUnREd2lwQVF5K2dY
            cmFkM3hmdjh1K3RYOHdGbUJZaWNQS0UKLS0tIGdyVENjUUtiUWRaQUlpa2ZxN1cx
            eWhjTjZtaXhnVStYS1hmdkRoTXJDdkkKJmlI6sPK/VxY3pjjHzT8R+PDhmqNp+m/
            1kPRLCJRkrAv+8vaJwyKA531Dl04pJw4QJOaw1C6yZBfColdNc0kQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T14:52:27Z"
    mac: ENC[AES256_GCM,data:awVVFNkKjDTcgeJ/Qb+iXYrrpbl0DlmntQWJmmKkMyBEiEyJiDGAg0Mh5nPoq7ZBohEAQm951Bg9DvTKgL2f46bQXigslEPpwJJH3USxrWBOQZQfAHhywKqs0urOwzNRm4sEwSQKRH1LpmiG++5XmhfZ6ipzqhX29fvrsHWtUcE=,iv:74eXD7d9rCCrjkcY3Su9wuEmDrfayUaRkqvJVUYbmcM=,tag:9nvBiZ1hyWeowSPCbKXaVg==,type:str]
    pgp:
        - created_at: "2024-08-04T11:08:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz9aZqoHT9PNAQ//TwkYgkSyHfHvJGxB7xIQMhfhUr0z+01oRNJGcP0IPZQO
            jVpFlS7J7CbwLDrk+ew5e8Qmex+D0LZFpCA73DkixaRaTjgwwAVltLwImYhX0j+j
            UFg86U1EU/yJHemDrDdLvindg9NklIImZIpJevDm8srtjaZAohsXFUuSs7oGAEOQ
            Hmp7Hj7eeSPBSrJbppfsbQZAA5QWcPf/+61JiM8k5fvReu+vTVkxWm0WgUyeWGnA
            FTT3nW8h8d9q3uC7DUJcqyi7fREM6TJH9spRxT4L9X1EjdxoMUWsHnjH4wuDV/e+
            AKvjB+LC0jmVn/y4sGl3Krr4NB0XCxEtBBJT3M4Mx8UnPNtnMCGcu56vMBUvZZbS
            v8p0WH9AXsM5zXLCYKzCcHRURjbtyf/0/fPafBIiEz6yMgWp0hSNA3XHEPjCLWOM
            oFcqdMwZpYySGXyi55mjt5MTS7cZ9g3YYQac2OMU+Ax1BeWUrbUWhUKmHusTIs15
            fxASd5erzda2i9XwF8ZdmgyRbQTVYLgLsTHm2wEVI1YahPWSv5lxgDwXcfghbS5r
            XAUkyfEwM/n9mmJBUrXtr9eNcN+8SNzzvzSh2IiEsv0T3GAw6qx8gBzC5p+rhQEZ
            DLU44ckAXAIvi8fQGxq4RgwDxOoX6w3BUZ3YcxztAouSJmahAP7zhsQgmaMHGTTS
            XgHXf1xWzqtSh4Z5HFEvNGWfh1gqxM/ypHZB7kVJ0hXQ28+IdMLa58a1sSXLOzJ3
            nR+VgiQxWRt121L9ShOToKlR9VnvbniblCRqvMo1xl+FSWEyiFHy0Yp/diuaMa0=
            =DhW+
            -----END PGP MESSAGE-----
          fp: 6528912C6687A3E2
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
