apiVersion: v1
kind: Service
metadata:
  name: proxbox-api
  namespace: netbox
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: proxbox-api
  type: ClusterIP
