apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxbox-api
  namespace: netbox
  labels:
    app: proxbox-api
spec:
  revisionHistoryLimit: 2
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: proxbox-api
  template:
    metadata:
      labels:
        app: proxbox-api
    spec:
      containers:
        - name: proxbox-api
          image: docker.io/emersonfelipesp/proxbox-api:latest
          imagePullPolicy: Always
          env:
            - name: PROXBOX_ALLOW_PLAINTEXT_CREDENTIALS
              value: 1
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: proxbox-api
              mountPath: /data
            - name: slash-dotlocal
              mountPath: /.local
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      schedulerName: default-scheduler
      volumes:
        - name: slash-dotlocal
          emptyDir: {}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: proxbox-api
      spec:
        accessModes: ["ReadWriteMany"]
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
        storageClassName: zfs-quick
