replicaCount: 1

image:
  repository: ghcr.io/klaernie/netbox
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

superuser:
  existingSecret: netbox-admin

# Skip the netbox-docker startup scripts which can pre-populate objects into a
# fresh NetBox installation. By default these do nothing, but they take a while
# to run, so we skip them. See:
# https://github.com/netbox-community/netbox-docker/tree/master/startup_scripts
skipStartupScripts: true

banner:
  # Optionally display a persistent banner at the top and/or bottom of every
  # page. HTML is allowed.
  top: ""
  bottom: ""

  # Text to include on the login page above the login form. HTML is allowed.
  login: ""

# Display full traceback of errors that occur when applying database
# migrations.
dbWaitDebug: false

# Email settings
email:
  server: debs.ak-online.be
  from: "netbox@netbox.ak-online.be"

# Exempt certain models from the enforcement of view permissions. Models listed
# here will be viewable by all users and by anonymous users. List models in the
# form `<app>.<model>`. Add '*' to this list to exempt all models.
exemptViewPermissions: []
#  - dcim.site
#  - dcim.region
#  - ipam.prefix

# Determine how many objects to display per page within a list. (Default: 50)
paginateCount: 50

# Enable installed plugins. Add the name of each plugin to the list.
plugins: ["netbox_topology_views", "netbox_proxbox"]

# Plugins configuration settings. These settings are used by various plugins
# that the user may have installed. Each key in the dictionary is the name of
# an installed plugin and its value is a dictionary of settings.
pluginsConfig:
  netbox_topology_views:
    enable_circuit_terminations: true
    draw_default_layout: true
    allow_coordinates_saving: true
  netbox_proxbox:
    proxmox:
      domain: "pve3.ak-online.be"
      http_port: 8006
      user: "root@pam"
      token:
        name: "netbox-proxbox"
        # token value is provided by the secret
      ssl: True
    # netbox is extended by token
    netbox:
      domain: "netbox.netbox.svc.cluster.local"
      http_port: 80
      ssl: False
      settings:
        virtualmachine_role_id: 19
        node_role_id: 20
        site_id: 1

# Time zone (default: UTC)
timeZone: Europe/Berlin

## Extra configuration settings
# You can pass additional YAML files to be loaded into NetBox's configuration.
# These can be passed as arbitrary configuration values set in the chart, or
# you can load arbitrary *.yaml keys from ConfigMaps and Secrets.
extraConfig:
  - secret:
      secretName: netbox-proxbox
      items:
        - key: proxbox.yaml
          path: proxbox.yaml
      optional: false

existingSecret: netbox-app

postgresql:
  enabled: false

externalDatabase:
  host: postgres.ak-online.be
  port: 5432
  database: netbox
  username: netbox
  existingSecretName: netbox-postgres
  existingSecretKey: db_password

  # The following settings apply when using the bundled PostgreSQL chart, too:
  sslMode: prefer
  connMaxAge: 300

redis:
  ## Deploy Redis using bundled chart
  # To use an external Redis instance, set this to false and configure the
  # settings under *both* tasksRedis *and* cachingRedis
  enabled: false
  storageClass: "zfs-quick"
  replica:
    count: 0

tasksRedis:
  database: 0
  ssl: false
  insecureSkipTlsVerify: false

  host: netbox-redis-master
  port: 6379
  existingSecretName: netbox-redis
  existingSecretKey: redis-password

cachingRedis:
  database: 1
  ssl: false
  insecureSkipTlsVerify: false

  host: netbox-redis-master
  port: 6379
  existingSecretName: netbox-redis
  existingSecretKey: redis-password

## Storage configuration for media
persistence:
  enabled: true
  storageClass: "zfs-quick"
  accessMode: ReadWriteMany
  size: 2Gi

reportsPersistence:
  enabled: true
  storageClass: "zfs-quick"
  accessMode: ReadWriteMany
  size: 1Gi

podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: true

service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        # You can manually specify the service name and service port if
        # required. This could be useful if for exemple you are using the AWS
        # ALB Ingress Controller and want to set up automatic SSL redirect.
        # https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/#redirect-traffic-from-http-to-https
        # - path: /*
        #   backend:
        #     serviceName: ssl-redirect
        #     servicePort: use-annotation
        #
        # Or you can let the template set it for you.
        # Both types of rule can be combined.
        # NB: You may also want to set the basePath above
        - /

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Configuration of Cron settings
housekeeping:
  enabled: true

# Worker for Netbox
# Only required for Netbox Jobs, e.g. Webhooks
worker:
  enabled: true
  replicaCount: 1
