resources:
  - _argocd.yaml
  - _cert-manager.yaml
  - _cnpg.yaml
  - _external-dns.yaml
  - _metallb-system.yaml
  - _reloader.yaml
  - _sops.yaml
  - _zfs-provisioner.yaml
  - abs.yaml
  - auth.yaml
  - default.yaml
  - elk.yaml
  - gatus.yaml
  - grafana.yaml
  - grocy.yaml
  - immich.yaml
  - influx.yaml
  - ingress-nginx.yaml
  - kube-system.yaml
  - kuma.yaml
  - ldap.yaml
  - magicmirror.yaml
  - netbox.yaml
  - patchman.yaml
  - rustdesk.yaml
  - vault.yaml
  - x11.yaml
  - zigbee2mqtt.yaml
