apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  project: default
  source:
    repoURL: https://github.com/klaernie/k8s-internal.git
    path: vault
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - ServerSideApply=true
