apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-apiserver
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: external
  tls:
    - hosts:
        - apiserver.k8s.ak-online.be
      secretName: tls-k8s
  rules:
    - host: apiserver.k8s.ak-online.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes
                port:
                  number: 443

