apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patchman
spec:
  project: internal
  source:
    repoURL: https://github.com/klaernie/k8s-internal.git
    path: patchman
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: patchman
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - ServerSideApply=true
