apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-data
  namespace: influx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zfs-bulk
  resources:
    requests:
      storage: 300Gi
