apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: influx
spec:
  ports:
    - name: influxdb-http
      port: 80
      targetPort: 8086
    - name: influxdb-typical
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
  type: LoadBalancer
