apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: influx-secrets
    namespace: influx
spec:
    secretTemplates:
        - name: influx-admin-token
          stringData:
            INFLUX_TOKEN: ENC[AES256_GCM,data:TAh8bnms7Wk7ZtQ3kzTVAEnX7E/WM4zhKtUxnKdSosYmSR/JXxRICKJfx6SBasQfnkks75VpwK4FdvqLvAmvetlQo9PkTdhyL6c5jicj1Ybz1kQnk668zQ==,iv:NfyZvkpIjvZQ7yjrSPkfX4HbTUNZFOCzlcA86ArN8mU=,tag:u27O1JEmq4z3Pyirrhp8jQ==,type:str]
        - name: telegraf
          stringData:
            INFLUX_TOKEN: ENC[AES256_GCM,data:nh0gjjvnnu6ncS+iMBICMJr1VFdLGBItUtN54e6McC11a33sQql0Auz4hWh+O2q9OP74U9k/aVy7nXF8MwMIw4/jePqJEGp9vNuddkKWHON92sCELFS6mQ==,iv:AdT3oIYzI6UH6jpJDltU0MkeVL00eWpkLeWoF8Ys5sg=,tag:BxmClc/fMP2c8qKWZdrePw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfxd6zqm4x755qpxd2h4fl5uqnu07hrpyv2cstdey0lg5lc5x47qzsvrn5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSmNiNWtqNEVvVmFtQjdp
            WTZTZ3crTWxJSEpzcWtKYStFdXkxVm1GNGhzCkNleFBYVFNoblZ1ZWw4NG9rYkN3
            eHB6cVo5K1phYnJqZnhUblB3M3R4amcKLS0tIGVmU3hDVjJMdkJSTVgrMlhsM29D
            TmZmTlFmU3NYU2dBdktpQ0tBSWtjOE0Ka/FqCPDIWqRXlRvyGM4JzAnoB3hVl7Oz
            YtvbnPO+XIz8JDHBETRj5+nltHQ7VJk23DnFIDvIeCcEvrvLBw9uSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T16:42:32Z"
    mac: ENC[AES256_GCM,data:90ihHpvvLe7FOgWq20qaoUEZ5T7UhffgZMorLeQePDbd1rtKWqTmkQMvtfYd6cCqDCG4mrhGyGJnw9eoO4wZ+NGSNxHfMr5htzWbOxZ0ij0mc8D1gWcqqY2sFJZBn+YDULBmY2JaAu22waDCkxKBC1NruoWPc86pRWLh1rXt140=,iv:tQrFiP/ZhSVk8FbNcbCW3qpZjz3FH+ZpmwDX4gbgHcE=,tag:G/puv4zY1hLMpOyyqJ/fFA==,type:str]
    pgp:
        - created_at: "2024-08-04T16:40:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz9aZqoHT9PNARAAnvG5dhQORg5Y+qKs/ot0XBeGS26W0eijlV0mSQgfXp/A
            6P9bC13zlpcMVU43Y/7QUtqglUpq+n4FpiWKUjAxN0BALA5OJ3705hAzSdhdYy1I
            Ukd4aS/jAM6YG/2MhkLa9CHRz1YF9HemHWEh+QmlTNuqQlLHsbIjLqu/ZP6zZDbW
            vvb6viWHqyFK7rghQDgtQrKWyc1P35l//pERAin0HPPfQGgvZBVvf8yd9dLI8DcX
            GbH/gHCdcbN0kq9QNss12AqwMECHaMJrpSg7X/ThnkTjp9hD9gaZu+K/9l0h8ycp
            fWgacEKvDE+VGoDo6J/ERop0ILjP7+XPYf1hPXkvywV9aqVAKWmGKlpoQjcinliu
            RWthz7hpxRTTFLMvnnxKf/R3YdFC118LQE96XfQYXEBB7SNIepLceJd/mFa1yoR4
            eZu4bQM18AK2OpY4Imam5ycEhaiCOvMBWg48cg9pHsxBEMZ8km3NHRv4ZQ5A2hcF
            7qIKjdkDZfVRPIpkwOC0RBzfWqx0JcIT9XbWaBIuNf4wrQZCSyeC8w8xgmGZGRVf
            bkTCr2E0pOIrdFKY9BRpxiu3D3CJnA5Zoi5A6Vv/f5T3AgQSXBpETMyyrlI7QZW9
            PYc+INRJfyLgR8L6wTyzq4n/5cIlV/TTdQjPNxWLKx8eJOulOH+YCprik0Kc66nS
            XAE24iUwDSasMj93GobYCRLVtF9wfMq9HkCi7JiUnmLk/UaypvZ7cT38guXFNWgs
            8mNH0/JFPAtMcS1SzH1TljC8hipMgn0fx9jw8//M1y/ya2zy4rH7CC4w0RwW
            =vYPN
            -----END PGP MESSAGE-----
          fp: 6528912C6687A3E2
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
