apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: secrets
  namespace: gatus
spec:
  secretTemplates:
    - name: rustfs-cnpg-credentials
      stringData:
        ACCESS_KEY_ID: ENC[AES256_GCM,data:ucqF4BzO+1XVwHqgeEm2pd5+YKk=,iv:7o6ILgav4vWxS2SlKixXtatBaDP7TLSapo1ETs0UKwc=,tag:E/bjl8gwvSss4D8C48udmw==,type:str]
        ACCESS_SECRET_KEY: ENC[AES256_GCM,data:w9bZgVdfRs5634nlDAdxX6DSueWEWOqcvLNS80LtlskFxFxWlh+hbg==,iv:XoKfztGIP7+y8ge3DmdndT4nqz0d/41ES2EiwYQVNCs=,tag:PlyKBpLHjX9Nlvrw1GkPtA==,type:str]
sops:
  age:
    - recipient: age1pfxd6zqm4x755qpxd2h4fl5uqnu07hrpyv2cstdey0lg5lc5x47qzsvrn5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1akJjMTBmN0IyNUdsK2JC
        c0dqMEE3RDhEVG1kQnU4eXMrdGNBTFlNWVhzCjRUNk5oa29sWGNPcUV0M1JpWXVY
        dC9VcWpGRzgyTXp3dlRkYlo2WVU0Z28KLS0tIEkyTnF6QlJKZk50L1YyWmhNNGlD
        RWRESmFjc1NqRWp5akZTd3EyellOVWcKHOZdXLA/afQFDjSgVaKeAiLtaX1bOdFf
        o+Yz0fPfCRNFIPJoVsVPhabA8/DazOjASoSChJY91/e8Qh3jVomTUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T17:27:04Z"
  mac: ENC[AES256_GCM,data:kBTWv6or5rXnLOxRgzmvco/8cpYK+kMmQod3TmmKZA3gxiNcoyZyXaoaoTeWjeeNwBlhye+hYDjM7mOkrxLJ9SWkUlZdbZ5REeepm/qVA+1xBNX92yBUIz7jAfXE/C3b026Sg7BhSo204H3vGqF+VfZ4AECspVjnXoBGXQ/fpiE=,iv:ttyz843jOJm6I3P+XFSDPXypzk2QVd1OnNgqLdNMRYI=,tag:kS/i8phyyEeHTydeZUmTPw==,type:str]
  pgp:
    - created_at: "2025-11-09T21:11:11Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAz9aZqoHT9PNAQ//YzUwoA/SETmoQpYx8vpyLdcLf/fhd2w7nP2OUBVp9xbd
        coXP1lrGWrWKu2/LMyfGVOl+eVmeZ/UWt72X1ZFCkuF4L9Yk9HbOssyf1TDPEBsZ
        zVkRc8ABo7ERTML5QhJDt7FTacjSD+lKkAWUSol38fmP+IpooMckwQOpYCKPyBhP
        U1qOT8MB0TqVRbpa3+jKUTqE5Xav7FYtouK3KuZgepMyC/TdhajCbU4cnXupL0Qa
        O3S4VuzVrl7m+FUwot/c5wm278lRq8NpScOXQSatNhhiiZS4RgV8LQT+IQYumEmK
        NjlR1jFIz2UquMKeRrPEB9gaumQcNpP/0hdNJZ3wtGZSbPEwvv9YzKBIR8HNA+U1
        3zSNiGNHo++92sw0prdvRz46Dlb8O2G0VBl96KrTZ3UoEUjSSrrzOh2l/XRH48Be
        qs7cdvWo5napt7fKnSZeoNHwsLG5FmQCWUhRff5jXagtvcMlD7ftM4df8BpmfKFi
        2w3G+jkssvexySnd2Kg1tapjEdMDnzkCNj0xxx2oJk2eYzhrNvl9SbvmN5csJi1a
        dz075+dL6AMmp0MD7+U2wMajTfUQQ4AKoqru5laCP/1PiTuMf0oHGooR7Rrlcw2j
        mjhihf1ZTMlqh3qj5amLGV1vvZvUOaUqbXFLotM1NKnpkAHp9wNkawdLHtll8anS
        XgExslP1kgwnHeBp6X50VStxmRIBjJOoU4K4QRqUWBEb/7q9wbdLwbPXBaZRBaKl
        NItzWJ5wRs7/qk3kweIe0qRXKWxtlY+CL7jrCFw3BI9tehdCss3T8/n6j+020QI=
        =z6qF
        -----END PGP MESSAGE-----
      fp: 6528912C6687A3E2
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
