apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak
  namespace: auth
  labels:
    app: keycloak
spec:
  description: "PostgreSQL for Keycloak"
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 1
  startDelay: 300
  stopDelay: 300

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak

  enableSuperuserAccess: true

  storage:
    storageClass: zfs-quick
    size: 2Gi
