apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-keycloak
  namespace: auth
  labels:
    app: keycloak
spec:
  description: "PostgreSQL for Keycloak"
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 1
  startDelay: 300
  stopDelay: 300

  bootstrap:
    # initdb:
    #   database: keycloak
    #   owner: keycloak
    recovery:
      source: origin

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: rustfs


  storage:
    storageClass: zfs-quick
    size: 2Gi

  managed:
    services:
      disabledDefaultServices: ["ro", "r"]

  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: rustfs
          serverName: pg-keycloak
