apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: keycloak
  namespace: augh
spec:
  schedule: "0 0 0 * * *"
  immediate: true
  backupOwnerReference: cluster
  cluster:
    name: pg-keycloak
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io

