apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-auth.yaml

  - secrets.enc.yaml

  - cluster-pg-keycloak.yaml
  - db-backup-store.yaml
  - db-scheduledbackup.yaml

  - certificate-keycloak.yaml
  # deploy keycloak operator
  - github.com/keycloak/keycloak-k8s-resources/kubernetes?ref=26.7.2
  # deploy the custom resource
  - keycloak.yaml
namespace: auth
