apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
    - protocol: TCP
      name: https
      port: 443
      targetPort: https
  selector:
    app: keycloak
  type: LoadBalancer
