apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: secrets
  namespace: sops
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:VgYy5Fqalg==,iv:Peqm/DJVdjlRg5Z19woCN0lYLMnl2k+5anGVxSRFqno=,tag:6joYZrj1IGN7M2m6aZb5PQ==,type:str]
      stringData:
        key.txt: ENC[AES256_GCM,data:Z/fmBXDRZnv9mbLuYBZjHdigx8yCMKCYfYCKp7Ki0krQyrARdf5kkI5AZ0VsTVh9ODWQBU4xGrFkgJ+J9NzzzWoyYYa7Dxg/gL6bFbN3LQdqK8esaJK4llPefKLR/BWfY8DkY1rbd0/vK20w+EPwP1dpiqfneCQwkIS4lDDNSU7Bzuh0sgpwzftwRvnMTxhhrnmTxNOe7NbI2cmShNayNXsdGWbH4q2UxdAViNyWDvXsBpy6yBwNeARb+ouh,iv:pBgMgLVS6o945bgMzN97+nEV0Z/WCg4jCJOm61Yst28=,tag:jIsQgobN7sJZHYaIi8oLcA==,type:str]
sops:
  age:
    - recipient: age1pfxd6zqm4x755qpxd2h4fl5uqnu07hrpyv2cstdey0lg5lc5x47qzsvrn5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeitDZ0RxM0tkLytDbGZ0
        Y1JXZ2U5a2xRQ3VKVWFxeGNBeHpPRm9DWWtFCnI1WjFOKzNGNXo5KzdITjc5SWox
        MTFJc3RaU3QrVzNNRHNkV0pVeHZzOTQKLS0tIE55SGdCaDJoVVRSMWtNaS91b0Ny
        S3R4bmJTeFplanBMdmdWOGNMaWRVQlEKq+pkk5vg6Wj9Yq6YGWD1qddOKqJdwaTm
        5vT+dUQ7K/D6xwjfkKOgk4lcwZIWY0l3c9xZOtEBJGqUX19MHb9IUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-05T12:56:00Z"
  mac: ENC[AES256_GCM,data:dDPchLAQANofp8w6xHycnoKYPheHgq5bGLvUlVZ8Ewx7Zv2w2Co3Il8JVmyjtqvtsBx6/n9xiJIiXvYKjMe0ywCrmlSz21occAa71iI2aHlRVcwdiv5XGev4tB6PMOkb7v5KuWwEXIpoazyTSTw4MmKAzE1H1dC5HM8tSH2D9EI=,iv:2WieRxVLVO8ik5fY1TiBhTHyD8guXUL98OuL1rzODUg=,tag:JONfsR5a7O6rb04EyfLyeQ==,type:str]
  pgp:
    - created_at: "2024-01-09T20:47:23Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAz9aZqoHT9PNARAApbFr8rDoPs08eezIADe/ktuchjHUjiYJqwoTYr8xY3mv
        z1WUgNqfcd4a8Ko4fI9BuUfTt7kGH6x0KBvODsDAxwGplbWJmt7//wC7pS7ONbGW
        ncKdU5E6puH8nrCLz8evL7hccEMa9PUgNisORLJ7CAnG25f4/s0qH84YeydaM/2E
        EOp5id5XcNHp7viaPgGMHp8v0ziYwGO4K76nu1hasvx4iwaeUPXx5x2Yk6iL5Yd3
        y3KLJmYfchV59xgCprTRNBKJEREVc6L9U+L1XVNCSUqPKjc2CYQArbnN9kSChT7Q
        RoRjjeQ4kpsFxMqaZYy152Hw+dl+fXDldWVq/7QMU1YSl8bSpQ0w3QtQ4KvKPVrd
        BHDZJf7i/gc4xytiVgaRUvggAZcAvFhBbHYUbYBWtVibqmw6+WfASp1XpTJgE7XS
        Z9XZE8K9569TolOhY2BCUdgBgkqKGPtU4JTS4pgXJxLD9X+xtTTj+gOMZrB7x9mT
        0r7L2dlvhk6Qwjecgc3wxUSUKa1fj6UyXnzs4RqJXxp2G6/p2+4XuZwdZVYHNWWM
        +cxsjehPFloxwOczz/1KBIcy5N3Tc78xF4X1ZqfkQLUOgQrpxxsncQr3dg7kzntp
        jQMv1F+T3DDOoIatsNQCsr2Am3Xc5JgGEj1QDbekNU5De8tlss6K5NHUg6cZHIXS
        XAGp6cjPmLI74XzvOqXL6oJiLB7rfpmrlrxcK+aYh96yWF7XToxM5zPPzHphGVXT
        pCwxZnToBYeLZR+/6JCXLPojy6HVw8KMZWm7aehHcQ47RcjBSFl5hfbfJy7H
        =kUpU
        -----END PGP MESSAGE-----
      fp: 6528912C6687A3E2
  encrypted_suffix: Templates
  version: 3.11.0
