endpoints:
  - name: cmx.ak-online.be - smtp
    url: tcp://cmx.ak-online.be:25
    group: cmx email
    conditions:
       - "[CONNECTED] == true"
    alerts:
      - type: email
      - type: discord

  - name: cmx.ak-online.be - smtps
    url: tls://cmx.ak-online.be:465
    group: cmx email
    conditions:
       - "[CONNECTED] == true"
       - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: email
      - type: discord

  - name: cmx.ak-online.be - submission
    url: starttls://cmx.ak-online.be:587
    group: cmx email
    conditions:
       - "[CONNECTED] == true"
       - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: email
      - type: discord

  - name: cmx.ak-online.be - imap
    url: tcp://cmx.ak-online.be:143
    group: cmx email
    conditions:
       - "[CONNECTED] == true"
    alerts:
      - type: email
      - type: discord

  - name: cmx.ak-online.be - imaps
    url: tls://cmx.ak-online.be:993
    group: cmx email
    conditions:
       - "[CONNECTED] == true"
       - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: email
      - type: discord
