endpoints:
  - name: family.trilium.cloud.ak-online.be
    url: https://family.trilium.cloud.ak-online.be
    group: services
    conditions:
      - '[STATUS] == 200'
      - '[CERTIFICATE_EXPIRATION] > 48h'
    alerts:
      - type: email
      - type: discord

  - name: matrix.cloud.ak-online.be
    url: https://matrix.cloud.ak-online.be
    group: services
    conditions:
      - '[STATUS] == 200'
      - '[CERTIFICATE_EXPIRATION] > 48h'
    alerts:
      - type: email
      - type: discord

  - name: vault.ak-online.be
    url: https://vault.ak-online.be
    group: services
    conditions:
      - '[STATUS] == 200'
      - '[CERTIFICATE_EXPIRATION] > 48h'
    alerts:
      - type: email
      - type: discord

  - name: keycloak.ak-online.be
    url: https://keycloak.ak-online.be
    group: services
    conditions:
      - '[STATUS] == 200'
      - '[CERTIFICATE_EXPIRATION] > 48h'
    alerts:
      - type: email
      - type: discord

  - name: immich.ak-online.be
    url: https://immich.ak-online.be
    group: services
    conditions:
      - '[STATUS] == 200'
      - '[CERTIFICATE_EXPIRATION] > 48h'
    alerts:
      - type: email
      - type: discord

  - name: grafana.ak-online.be
    url: https://grafana.ak-online.be
    group: services
    conditions:
      - '[STATUS] == 200'
      - '[CERTIFICATE_EXPIRATION] > 48h'
    alerts:
      - type: email
      - type: discord

  - name: s-mm.magicmirror.k8s.ak-online.be
    url: http://s-mm.magicmirror.k8s.ak-online.be
    group: services
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: email
      - type: discord

  - name: xl-mm.magicmirror.k8s.ak-online.be
    url: http://xl-mm.magicmirror.k8s.ak-online.be
    group: services
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: email
      - type: discord
