endpoints:
  - name: firewall one
    url: icmp://fw1.ak-online.be
    group: infrastructure
    conditions:
      - '[CONNECTED] == true'
    alerts:
      - type: email
      - type: discord

  - name: firewall two
    url: icmp://fw2.ak-online.be
    group: infrastructure
    conditions:
      - '[CONNECTED] == true'
    alerts:
      - type: email
      - type: discord

  - name: Cable Gateway
    url: icmp://24.134.172.58
    group: infrastructure
    conditions:
      - '[CONNECTED] == true'
    alerts:
      - type: email
      - type: discord

  - name: Cable Modem
    url: icmp://cable.ak-online.be
    group: infrastructure
    conditions:
      - '[CONNECTED] == true'
    alerts:
      - type: email
      - type: discord

  - name: Google DNS
    url: icmp://8.8.8.8
    group: infrastructure
    conditions:
      - '[CONNECTED] == true'
    alerts:
      - type: email
      - type: discord

  - name: InfluxDB
    url: http://db.influx.k8s.ak-online.be/ping
    group: infrastructure
    conditions:
      - '[STATUS] == 204'
      - '[CONNECTED] == true'
    alerts:
      - type: email
      - type: discord

  - name: ns1
    url: ns1.ak-online.be
    dns:
      query-name: ns1.ak-online.be
      query-type: A
    group: infrastructure
    conditions:
      - '[CONNECTED] == true'
      - '[BODY] == 92.51.149.177'
      - "[DNS_RCODE] == NOERROR"
    alerts:
      - type: email
      - type: discord

  - name: ns2
    url: ns2.ak-online.be
    dns:
      query-name: ns1.ak-online.be
      query-type: A
    group: infrastructure
    conditions:
      - '[CONNECTED] == true'
      - '[BODY] == 92.51.149.177'
      - "[DNS_RCODE] == NOERROR"
    alerts:
      - type: email
      - type: discord

  - name: zfs-nfs-quick
    url: icmp://zfs-nfs-quick.ak-online.be
    group: infrastructure
    conditions:
      - '[CONNECTED] == true'
    alerts:
      - type: email
      - type: discord

  - name: zfs-nfs-bulk
    url: icmp://zfs-nfs-bulk.ak-online.be
    group: infrastructure
    conditions:
      - '[CONNECTED] == true'
    alerts:
      - type: email
      - type: discord
