endpoints:
  - name: debs.ak-online.be - smtp
    url: tcp://debs.ak-online.be:25
    group: debs email
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: email
      - type: discord

  - name: debs.ak-online.be - smtps
    url: tls://debs.ak-online.be:465
    group: debs email
    conditions:
      - "[CONNECTED] == true"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: email
      - type: discord

  - name: debs.ak-online.be - submission
    url: starttls://debs.ak-online.be:587
    group: debs email
    conditions:
      - "[CONNECTED] == true"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: email
      - type: discord

  - name: debs.ak-online.be - imap
    url: tcp://debs.ak-online.be:143
    group: debs email
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: email
      - type: discord

  - name: debs.ak-online.be - imaps
    url: tls://debs.ak-online.be:993
    group: debs email
    conditions:
      - "[CONNECTED] == true"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: email
      - type: discord
