apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: grafana
  namespace: grafana
spec:
  secretTemplates:
    - name: grafana
      stringData:
        dbpassword: ENC[AES256_GCM,data:uU0mBAuI549Bhq8mzsOkQTKFMwKDyMDy8wFYoxG2SvLIZVtgHqQoftETSo/18qoPhOBUCcULeqeKzZqvBNOzx5+Ng1sSXYL6xF8=,iv:KKo0IVVYb5ozi294tHp6nv2FqHqmB1ulKH9tOB9/nyA=,tag:rI9Ae4l5ubRTIz5qZoryDQ==,type:str]
        encsecret: ENC[AES256_GCM,data:I9ZUQm4yCNusbTdjPtI0q3paUGVC,iv:KsP696HBiX68L07OOnxRNZFgIJY7vEYxf4EqvyeyiLg=,tag:ZDGD1mp0eSat9WzSTBuziA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pfxd6zqm4x755qpxd2h4fl5uqnu07hrpyv2cstdey0lg5lc5x47qzsvrn5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZGoycHREczRSSkZNNkk5
        aXRBdzBJSGloMkNZSzVFMGlkVXpvcmJSYWlFCjhqd0x5ODZocUhDeDJEaWtJajUr
        ZWVmWTI0c2hmMHc0dWpBNWZRYkpyelEKLS0tIFlxd0c0eURsdU9UbTluOWRZcjhu
        eTYzV1VRTjZYc1M3aGxUNTBpeXlGdjgKI5m83ng1gYd7BLfxQu8TfT0ScL/QOvBN
        SU/NzfUG4puUgs5kZdLzOpNLVasSXO2sciM03Sm11/5U5DhflP2svw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-01T14:05:48Z"
  mac: ENC[AES256_GCM,data:ymlGS7K3WwIgUvAbdaGhcQAsNE5zsK+GvzqQc2P161DEVJ7XtLkZR21Cmkr8nrvNMgJ1eaFgdn3c3JLNSm7BZgx7nfARaCEtY2Simqbh91fwFVaAgF6MgnsAe5OynThQOesiro5LjqZqoBgOA9v+jyOl7AQFVfp+oCFjepdqaIQ=,iv:es/qvXO6OT/rPnoe3YU2zlsS71B41r1AOXqSLaZH2Hw=,tag:/kiYifApAj413vHmBi+phw==,type:str]
  pgp:
    - created_at: "2024-05-01T14:05:47Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAz9aZqoHT9PNAQ//VAp3RbDnrXekINqMilrGIiMAOS6HjNJQr/ueGgpxvzAt
        yNztUn3aZIISVgpPEdBAKeuh2jfwvCZlobAXYMnAwrY/Aa0Ei+Ibo1h8RbCSQTeW
        WRadaTREYXW/GQ7ZdxzUQ+8Zyt8lQt6ObmjorAVDolPOdYygVCkVPoY9/TFhNcz6
        U+x1xQfKYb4hctry8LvwZMeqzOmx+cKKqDBVxKfgp+3hrlVNCvsU9W1BFo9rN49f
        126uIcLfnWcrSwzlUaZCRS+gAJFbm9JSEohvpnS+tg6m+hPoZ3Gn6F0QV4BA2JJ+
        Hswiy9qF3brFNikXMPwOCpj6g8143ZgTfS470d8I+I9iRNtSgQOBkZWaozYh73ZX
        im+GrJmdvUA/8q24J55bmucN+hhxYxhwkisM7/OD7JMOnrry7A324EvBRWF9yiAh
        axHOxMpmGYnAz8+yJxBSGDbkC93RVFw7byawMYXcT2gI7mb0rmHRZ5tWNnpiWXzN
        oFaCdTwTYf6uSgoB3m7uk2QA5smLleX/8ZI+6iUQZXDsZ1ISOzl5JbNKF9TMc6+c
        g/E5NstE13nJAN1/qbuAiNeDTJvVjt94qiNkfVHf+2wQFvQnAqX6o88XFNRb0eOO
        ZLrqLfmz9zsJgC0sYYJE8WEhoM7sdeqaf6IvjkjC033852fFfWnpQ6HGdLpdNbTS
        XgE1ADFeXNdh3IGzranKxIrWrLKd4RRhV/GAywtidiTisIj9mWJUsP+CNzFmbalk
        Pg/Q5P35ZvA1ubA4JsgYNLDOVYI4qu77LIaMTo/aVRe/06muWdqLfdY1v+KWIBQ=
        =gVwk
        -----END PGP MESSAGE-----
      fp: 6528912C6687A3E2
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
