apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magicmirror-data
  namespace: magicmirror
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zfs-quick
  resources:
    requests:
      storage: 5Gi
