apiVersion: apps/v1
kind: Deployment
metadata:
  name: calserv
  namespace: magicmirror
spec:
  selector:
    matchLabels:
      app: calserv
  replicas: 1
  template:
    metadata:
      labels:
        app: calserv
    spec:
      containers:
        - name: nginx
          image: nginx:1.29.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nfs
              mountPath: "/usr/share/nginx/html"
              subPath: calendars
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: magicmirror-data

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: calserv
  name: calserv
  namespace: magicmirror
spec:
  ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: calserv
  sessionAffinity: None
  type: ClusterIP
