apiVersion: v1
data:
  config: |
    var config = {
            address: "0.0.0.0",
            port: 80,
            ipWhitelist: [],

            language: "en",
            timeFormat: 24,
            units: "metric",
            timezone: "Europe/Berlin",

            modules: [
                    {
                            module: "alert",
                    },
                    {
                            module: "clock",
                            position: "top_left",
                            config:{
                                    showWeek: true,
                                    clockBold: true,
                            }
                    },
                    {
                            module: "weather",
                            position: "top_left",
                            config: {
                                    type: "current",
                                    weatherProvider: "openweathermap",
                                    location: "Dresden, Germany",
                                    locationID: "2935022",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
                                    apiKey: "${OWM_APIKEY}"
                            }
                    },
                    {
                            module: 'MMM-CalendarExt2',
                            config: {
                                    rotateInterval: 60*1000,
                                    deduplicateEventsOn: [
                                            "startDate", "endDate", "title",
                                    ],
                                    scenes:[
                                            {
                                                    name: "DEFAULT",
                                                    views: ["current","upcoming"],
                                            },
                                    ],
                                    views:[
                                            {
                                                    name: "current",
                                                    mode: "current",
                                                    position: "top_right",
                                                    maxDays: 1,
                                                    locale: "en",
                                                    hideOverflow: false,
                                                    filterPassedEvent: true,
                                            },
                                            {
                                                    name: "upcoming",
                                                    mode: "upcoming",
                                                    position: "top_right",
                                                    maxDays: 3,
                                                    locale: "en",
                                                    hideOverflow: false,
                                                    filterPassedEvent: true,
                                                    useEventTimeRelative: false,
                                            },
                                    ],
                                    calendars: [
                                            {
                                                    name: "Anja",
                                                    url: "http://calserv/AnjaPrivate.ics",
                                            },
                                            {
                                                    name: "Andre",
                                                    url: "http://calserv/AndrePrivate.ics",
                                            },
                                            {
                                                    name: "Family",
                                                    url: "http://calserv/Family.ics",
                                            },
                                            {
                                                    name: "Tobi",
                                                    url: "http://calserv/TobiPrivate.ics",
                                                    filter: (event) => {
                                                            if (event.title == "Schule") {
                                                                    return false
                                                            }
                                                            return true
                                                    },
                                            },
                                            {
                                                    name: "Tobi Shared",
                                                    url: "http://calserv/TobiShared.ics",
                                            },
                                            {
                                                    name: "Tobi Lernsax",
                                                    url: "http://calserv/Lernsax.ics",
                                                    filter: (event) => {
                                                            if (event.title.startsWith("11:")) {
                                                                    return false
                                                            }
                                                            if (event.title.startsWith("10:")) {
                                                                    return false
                                                            }
                                                            if (event.title.startsWith("9S")) {
                                                                    return false
                                                            }
                                                            if (event.title.startsWith("9:")) {
                                                                    return false
                                                            }
                                                            if (event.title.startsWith("8S")) {
                                                                    return false
                                                            }
                                                            if (event.title.startsWith("8:")) {
                                                                    return false
                                                            }
                                                            if (event.title.startsWith("7S")) {
                                                                    return false
                                                            }
                                                            if (event.title.startsWith("7:")) {
                                                                    return false
                                                            }
                                                            if (event.title.startsWith("6S")) {
                                                                    return false
                                                            }
                                                            if (event.title.startsWith("6:")) {
                                                                    return false
                                                            }
                                                            if (event.title.startsWith("5S")) {
                                                                    return false
                                                            }
                                                            if (event.title.startsWith("5:")) {
                                                                    return false
                                                            }
                                                            return true
                                                    },
                                            },
                                            {
                                                    name: "Tanzkalender",
                                                    url: "http://calserv/Tanzkalender.ics",
                                            },
                                    ],
                            },
                    },
                    {
                      module: 'MMM-Cursor',
                      config: {
                        timeout: 2500
                      }
                    }
            ]

    };

    /*************** DO NOT EDIT THE LINE BELOW ***************/
    if (typeof module !== "undefined") {module.exports = config;}
  css-custom: |
    /*****************************************************
     * Magic Mirror                                      *
     * Custom CSS                                        *
     *                                                   *
     * By Michael Teeuw http://michaelteeuw.nl           *
     * MIT Licensed.                                     *
     *                                                   *
     * Add any custom CSS below.                         *
     * Changes to this files will be ignored by GIT. *
     *****************************************************/

    html {
            cursor: auto;
    }

    body {
            margin: 10px;
            height: calc(100% - 20px);
            width: calc(100% - 30px);
    }

    .region.top.right,
    .region.top.left,
    .region.top.center {
            min-width: 410px;
    }

    .CX2 .current .eventCount_0 {
            display: none;
    }
    .CX2 .agenda .eventSub {
            display:none;
    }
    .CX2 .daily .fullday .eventTime {
            display:none;
    }
    .CX2 .slot > .slotContent {
            background: none;
    }
    .CX2 .slot .event{
            background: none;
    }
    .CX2 .slot .slotHeader{
            background-color: inherit;
            text-transform: uppercase;
            font-size: 15px;
            font-family: "Roboto Condensed", Arial, Helvetica, sans-serif;
            font-weight: 400;
            border-bottom: 1px solid #666;
            line-height: 15px;
            padding-bottom: 5px;
            margin-bottom: 10px;
            color: #999;
    }
    .CX2 .today .slotHeader * {
            color: inherit;
    }
    .CX2 .event.fullday {
            color: inherit;
    }
    .CX2 .slot .slotFooter {
            display: none;
    }
    .CX2 .event {
            border-left: #000000 solid;
    }
    .CX2 .event[data-calendar-name="Andre"],
    .CX2 .event[data-calendar-name="Andre Work"] {
            /*color: #ce4138;*/
            border-left: #9517ab solid;
    }
    .CX2 .event[data-calendar-name="Anja"],
    .CX2 .event[data-calendar-name="Anja Work"] {
            /*color: #c632ff;*/
            border-left: #d12138 solid;
    }
    .CX2 .event[data-calendar-name="Tobi"],
    .CX2 .event[data-calendar-name="Tobi Lernsax"],
    .CX2 .event[data-calendar-name="Tobi Shared"] {
            /*color: #d2cf2a;*/
            border-left: #d2cf2a solid;
    }
    .CX2 .event[data-calendar-name="Tanzkalender"] {
            border-left: #4a9f16 solid;
    }

    .CX2 .event[data-busystatus="BUSY"] .eventTitle {
            /* color: #c632ff; */
    }

    .CX2 .event[data-busystatus="OOF"] .eventTitle {
            color: #4c4dba;
    }

    .CX2 .event[data-busystatus="FREE"] .eventTitle {
            /* color: #444444; */
    }

    .CX2 .event[data-busystatus="TENTATIVE"] .eventTitle {
            color: #444444;
    }

    #SPOTIFY_BACKGROUND {
      display: none;
    }

    .MMM-mqtt .value {
            font-size: 10pt;
    }
kind: ConfigMap
metadata:
  name: s
  namespace: magicmirror
