apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: xl-mm
  name: xl-mm
  namespace: magicmirror
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xl-mm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: xl-mm
        kind: magic-mirror
    spec:
      containers:
        - image: ghcr.io/klaernie/docker-magicmirror:v2.29.0
          imagePullPolicy: Always
          name: mm
          resources: {}
          env:
            - name: TZ
              value: "Europe/Berlin"
          envFrom:
            - secretRef:
                name: secrets
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: config
              mountPath: "/opt/magic_mirror/config/config.js.template"
              subPath: config.js.template
            - name: config
              mountPath: "/opt/magic_mirror/css/custom.css"
              subPath: "custom.css"
            - name: nfs
              mountPath: "/opt/magic_mirror/modules"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: magicmirror-data
        - name: config
          configMap:
            name: xl
            items:
              - key: config
                path: config.js.template
              - key: css-custom
                path: custom.css
status: {}
