resources:
  - namespace-magicmirror.yaml
  - persistentvolumeclaim-magicmirror-data.yaml

  - deployment-calserv.yaml
  - service-calserv.yaml
  - deployment-vdirsyncer.yaml

  - certificate-s-mm.yaml
  - deployment-s-mm.yaml
  - service-s-mm.yaml

  - deployment-xl-mm.yaml
  - service-xl-mm.yaml

  - secrets.enc.yaml

namespace: magicmirror

configMapGenerator:
  - name: s
    files:
      - s-config/config.js
      - s-config/custom.css
  - name: xl
    files:
      - xl-config/config.js
      - xl-config/custom.css
  - name: hotpatch
    files:
      - hotpatch.sh
      #- 4092.patch
