---
apiVersion: v1
kind: Service
metadata:
  name: grocy
  namespace: grocy
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    name: grocy
  type: LoadBalancer
  externalTrafficPolicy: Cluster
