apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
spec:
  instances: 1

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  postgresql:
    parameters:
      max_connections: "500"
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
   # disable initdb, since we can restore from backup.
   # For anybody starting afresh, comment out recovery: and uncomment initdb:
   # initdb:
   #   # TODO: Use managed extensions (pg 18)
   #   postInitApplicationSQL:
   #     # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
   #     - CREATE EXTENSION vchord CASCADE;
   #     - CREATE EXTENSION earthdistance CASCADE;
    recovery:
      source: origin

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: rustfs

  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: zfs-quick

  managed:
    services:
      disabledDefaultServices: ["ro", "r"]

  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: rustfs
          serverName: immich-db
