apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  claimRef:
    name: immich-pvc
    namespace: immich
  nfs:
    path: /media/Seven/Immich
    server: mainframe.ak-online.be
