kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-pvc
  namespace: immich
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  volumeName: immich-pv
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: immich-pv
spec:
  claimRef:
    name: immich-pvc
    namespace: immich
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    server: mainframe.ak-online.be
    path: /media/Seven/Immich
