.contexts.talos.endpoints = [ "talos" ,"talos-api01" ,"talos-api02" ,"talos-api03" ]
| .contexts.talos.nodes = [ "talos-api01" ,"talos-api02" ,"talos-api03" ,"talos-w01" ,"talos-w02" ,"talos-w03" ,"talos-w04" ,"talos-w05" ]
