apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kandre+intk8s@ak-online.be
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          # see https://docs.cert-manager.io/en/release-0.11/tasks/issuers/setup-acme/dns01/rfc2136.html
          rfc2136:
              nameserver: ns1.ak-online.be
              tsigKeyName: k8s.ak-online.be
              tsigAlgorithm: HMACSHA256

              # create with kubectl -n cert-manager create secret generic tsig-secret --from-literal=key=
              tsigSecretSecretRef:
                name: tsig-secret
                key: key
