resources:
  - namespace.yaml
  - persistentvolumeclaim-rustdesk-pvc.yaml
  - deployment-rustdesk-server.yaml
  - service-rustdesk.yaml
  - service-rustdesk-com.yaml
  - ingress-rustdesk.yaml

namespace: rustdesk
