apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-pvc
spec:
  storageClassName: zfs-quick
  accessModes:
    - ReadWriteOnce # RWM would be available only with pro version
  resources:
    requests:
      storage: 1Gi
