apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vault
  namespace: vault
spec:
  schedule: "0 0 0 * * *"
  immediate: true
  backupOwnerReference: cluster
  cluster:
    name: pg-vault
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io

