apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault
  namespace: vault
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: zfs-quick
