apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elk
spec:
  # renovate: datasource=github-releases depName=elasticsearch packageName=elastic/elasticsearch
  version: 8.15.2
  nodeSets:

  - name: gen2
    count: 3
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 75Gi
        storageClassName: zfs-bulk
