apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: ldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: LoadBalancer
  ports:
    - name: tcp-ldap
      port: 389
      targetPort: tcp-ldap
    - name: tcp-ldaps
      port: 636
      targetPort: tcp-ldaps
  selector:
    app.kubernetes.io/name: openldap
