
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-data-uptime-kuma-0
  namespace: kuma
spec:
  accessModes: ["ReadWriteMany"]
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: zfs-quick
