# This pod is mostly a copy of the one in the STS, but configured to never
# autorestart so performing a major version upgrade is feasible

apiVersion: v1
kind: Pod
metadata:
  name: uptime-kuma
  namespace: kuma
spec:
  restartPolicy: Never
  containers:
    - name: uptime-kuma
      image: louislam/uptime-kuma:2.0.2
      env:
        - name: UPTIME_KUMA_PORT
          value: "3001"
        - name: PORT
          value: "3001"
        - name: NODE_EXTRA_CA_CERTS
          value: /certs/ca-certificates.crt
      ports:
        - name: uptime-kuma
          containerPort: 3001
          protocol: TCP
      volumeMounts:
        - name: kuma-data
          mountPath: /app/data
        - name: ca-bundle-cm
          mountPath: /certs
      #securityContext:
      #  allowPrivilegeEscalation: false
      #  capabilities:
      #    drop: ["ALL"]
      #  seccompProfile:
      #    type: RuntimeDefault
  volumes:
    - name: ca-bundle-cm
      configMap:
        name: ca-bundle
    - name: kuma-data
      persistentVolumeClaim:
        claimName: kuma-data-uptime-kuma-0
