apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt-app
  namespace: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  clusterIP: None
  selector:
    app: zigbee2mqtt
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web
