apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  namespace: zigbee2mqtt
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zfs-quick
  resources:
    requests:
      storage: 2Gi
