apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: zigbee2mqtt
  serviceName: zigbee2mqtt-app
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: zigbee2mqtt
          imagePullPolicy: Always
          # renovate: datasource=github-tags depName=koenkk/zigbee2mqtt
          image: ghcr.io/koenkk/zigbee2mqtt:2.4.0
          ports:
            - containerPort: 8080
              name: web
          volumeMounts:
            - name: datadir
              mountPath: /app/data
          env:
            - name: TZ
              value: "Europe/Berlin"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
