name: 'deployment'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/k8s-set-context@v4
        id: setcontext
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: create sops/key.txt
        run:
          echo '${{ secrets.SOPS_KEY }}' > _sops/key.txt

      - name: generate manifests
        id: bake
        uses: azure/k8s-bake@v3
        with:
          renderEngine: 'kustomize'
          kustomizationPath: '.'
          arguments: |
            --enable-helm
          kubectl-version: 'latest'

      - name: deploy
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          kubectl apply --server-side -f '${{ steps.bake.outputs.manifestsBundle }}'

      #- uses: Azure/k8s-deploy@v4
      #  with:
      #    manifests: ${{ steps.bake.outputs.manifestsBundle }}
      #    kubectl-version: 'latest'
