name: 'deployment'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/k8s-set-context@v1
        id: setcontext
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - uses: azure/k8s-bake@v3
        with:
          renderEngine: 'kustomize'
          kustomizationPath: '.'
          arguments: |
            --enable-helm
          kubectl-version: 'latest'

      - name: deploy
        run: |
          kubectl apply --server-side -f '${{ steps.bake.outputs.manifestsBundle }}'

      #- uses: Azure/k8s-deploy@v4
      #  with:
      #    manifests: ${{ steps.bake.outputs.manifestsBundle }}
      #    kubectl-version: 'latest'
